name: Publish

on:
    push:
        tags:
            - "v*"

jobs:
    publish:
        name: Publish
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  cache: "yarn"
                  registry-url: "https://registry.npmjs.org"

            - name: Create .npmrc file
              run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc

            - name: Install NPM dependencies
              run: yarn install

            - name: Lint
              run: yarn lint

            - name: Build
              run: yarn build-ci

            - name: Publish
              run: cd packages/lib && yarn release-ci
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
